### PR TITLE
Sync some components with UPU

### PR DESCRIPTION
**Pull request by NovaRain**
* Add ammo damage formula options to the installer.
* Update gl_k_walking_speed script and upu.ini.

### CODE REVIEW

**Comment by phobos2077** [comment]
Will this finally fix walking speed log spam? :)

**Comment by NovaRain** [comment]
What log spam?

**Comment by NovaRain** [comment]
> Will this finally fix walking speed log spam? :)

Log spam? You mean the line `ndebug("set fps to " + cur_frame_count + " in " + path);`?

**Comment by phobos2077** [comment]
> Log spam? You mean the line

Yes.

**Comment by burner1024** [comment]
Thanks!

**Pull request merged**
