### PR TITLE
Adjusting orthography for combatai.msg.

### PR DESCRIPTION
**Pull request by Anarcho-Bolshevik**
Here are some modifications that I made to the orthography.

### CODE REVIEW

**Comment by Anarcho-Bolshevik** [comment]
Fuck fuck fuck LET ME EDIT MY OWN FUCKING FILE YOU FUCKS!

**Comment by NovaRain** [comment]
Fallout 2 is a 1998 game and does not support UTF-8 text file, so for Kitsune's combat message the slang "Cào!" won't display correctly.

**Comment by Anarcho-Bolshevik** [comment]
I can assure you that the `à` [was present in the original file](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/text/english/game/combatai.msg), otherwise I would have left such an alien word like that alone!

**Comment by NovaRain** [comment]
> I can assure you that the `à` [was present in the original file](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/data/text/english/game/combatai.msg), otherwise I would have left such an alien word like that alone!

I know it's present in the original text file, what I mean is your text editor probably converted its encoding to UTF-8 and you didn't notice that. so the character is actually garbled in ASCII encoding:
(_Left_: original, _Right_: msg file from your pull request)
encoding

How it's displayed in the game:
(_Up_: original, _Down_: msg file from your pull request)
scr00001

**Comment by Anarcho-Bolshevik** [comment]
Sigh… all right, I updated the file. Is it fixed now?

**Comment by NovaRain** [comment]
> Sigh… all right, I updated the file. Is it fixed now?

No, still garbled text.
compare
Here's the file with character encoding fixed: [combatai_enc.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9348193/combatai_enc.zip)

**Comment by Anarcho-Bolshevik** [comment]
What? Why are you showing that version again? I translated the characters like you told me.

**Comment by Lexx2k** [comment]
It's not what the file visually shows. It needs to be encoded differently. Are you editing via github web editor? If so, that will very likely break the encoding.

That said, I'm not sure if I agree with all of your changes. Some things are clearly done the way they are for style or speech habits.

**Comment by NovaRain** [comment]
> What? Why are you showing that version again? I translated the characters like you told me.

Your edit doesn't really "translate" those Unicode-encoded characters **back** to their original encoding (one character takes one byte), instead you just split them into multiple bytes. For example the `é` character was `0xE9`, in your file it's `0C383C2A9` (4 bytes).

**Comment by Anarcho-Bolshevik** [comment]
Are you serious…? GitHub’s interface is **_so_** clunky that it can’t even accomplish something as basic as handling character sets properly…? Wow. This website is even worse than I thought. But don’t worry, I’ll shitcan this thread, then you won’t have to care about it anymore. You are welcome.

**Comment by Lexx2k** [comment]
lol, someone's a bit sensitive over there.

You have to use the desktop / software version to checkout the files, edit them with notepad, and then push them back up. That's simply how it is and not our fault.

**Comment by burner1024** [comment]
I suggest VScode for editing the files.

**Comment by Anarcho-Bolshevik** [comment]
Take three: [ass.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9379507/ass.zip)

I didn’t use Github to make this, so hopefully this one will actually be useful. (Also, I left the extra full stops, question marks and exclamation marks alone even though I think that they’re redundant. I left most of the ellipses alone, too.)

**Pull request closed without merging**
