### PR TITLE
Reduced chance of meeting Kaga

### PR DESCRIPTION
**Pull request by egornovivan**

### CODE REVIEW

**Comment by burner1024** [comment]
why?

**Comment by egornovivan** [comment]
Non-combat builds have a very hard time with this Kaga

**Comment by burner1024** [comment]
I don't really like Kaga myself. But you don't have to fight him, you can just run away.
I prefer to avoid changing things that are matter of taste. A better option would be provide non-combat builds a possibility to solve problems in their own, non-combat ways.
And yet another option is to move Kaga encounters into global script fully, the way ettu does. And then make the chance configurable in the ini.
It's not something I want to take on myself, though.

**Comment by egornovivan** [comment]
The problem is that you can't escape from Kaga. Especially if the Kaga minions make 2 moves in a row.
https://rutracker.org/forum/viewtopic.php?p=81535844#81535844
https://rutracker.org/forum/viewtopic.php?p=81536829#81536829

**Comment by burner1024** [comment]
ok, but everything else I said still stands

**Comment by NovaRain** [comment]
I remember back in the day of RP 1.2 there's a way to persuade Kaga out of revenge on his second encounter. There's even a funny way to kill him with a riddle during dialogue, but it got removed in RP 2.0.

**Comment by burner1024** [comment]
Resolution: too arbitrary and doesn't really address the issue. However, if a better solution is provided, it will be considered.

**Pull request closed without merging**
