### PR TITLE
Update acnagor.msg

### PR DESCRIPTION
**Pull request by Fasciana**
missed this one before, but I couldn't edit my first pull request anymore, that's why this second one.

### CODE REVIEW

**Comment by burner1024** [comment]
Same as #94

**Comment by Fasciana** [comment]
Since I'm new, can you be more specific, please?

What do you mean exactly do you mean?

Will the female options at https://tra.bgforge.net/projects/fallout/rp/de/ work for those cases?

Please answer since some things are pretty confusing to me!

**Comment by burner1024** [comment]
_Every_ option on the site should work. If something doesn't, it's likely a bug and should be reported to the forum.
I'm not sure what makes you think that female one is any different. It is described [here](https://forums.bgforge.net/viewtopic.php?f=2&t=28).
And feel free to ask any other questions on the forum, too.

**Comment by Fasciana** [comment]
> _Every_ option on the site should work. If something doesn't, it's likely a bug and should be reported to the forum.
> I'm not sure what makes you think that female one is any different. It is described [here](https://forums.bgforge.net/viewtopic.php?f=2&t=28).
> And feel free to ask any other questions on the forum, too.

That wasn't quite what I need to know. I refered to this "Direct edits won't work. Use the option in the system." 

Which options do you mean and where to find them? 

Secondly I wanted to know, if the female option for translation would work, because I am not able to test/check my changes!!! When I'm doing them here: https://tra.bgforge.net/projects/fallout/rp/de/  because I have to wait until the changes are either transfered/pulled into the code or build into an update.

Here's an example for clearfication - hopefully: 
https://tra.bgforge.net/translate/fallout/rp/de/checksum=&offset=&q=hello+cousin&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=  

here are stated two lines (200 and 201), both are related to the cousin - one for male and one for female players. That's clear so far to me.

But I don't know when I check the female options, if the system automatically refering to line 201 because here it should be Cousine instead of Cousin in German. Also I'm confused because it's not the player talking, it's the npc that who refers to my gender. I'm a none native English speaking person that makes some things pretty complicated.

And yes I read the instructions to female language but that wasn't any help to my confusion at all.

**Comment by burner1024** [comment]
> That wasn't quite what I need to know. I refered to this "Direct edits won't work. Use the option in the system."
>
> Which options do you mean and where to find them?

I mean https://forums.bgforge.net/viewtopic.php?f=2&t=28.
The rest of the questions, please direct to the forum.

**Pull request closed without merging**
