### PR TITLE
Map changes merge attempt

### PR DESCRIPTION
**Pull request by phobos2077**
I think it might be time to finally merge these changes. There were no conflicts with the master. And several people have play-tested these maps already.

Not sure what to do with msg changes though. Probably need to update one of those po files or something.

### CODE REVIEW

**Comment by burner1024** [comment]
I know there's no conflict, it was never in question...

**Comment by phobos2077** [comment]
So, what do we need to do to get this merge approved?

**Comment by burner1024** [comment]
As I said, I don't know.

**Comment by Lexx2k** [comment]
Personally I love the new maps. They look so much better and more fine tuned than the old RP maps, which had way too much crappy scenery clutter.

**Comment by burner1024** [comment]
I don't have any issue with changes to RP-only maps, it's the other 150+ changed maps that concern me.

**Comment by Lexx2k** [comment]
Those are exactly the maps that I like more now. I always hated the new RP locations like Abby, EPA, etc. Though even those look better now (still won't visit the locations, though).

**Comment by burner1024** [comment]
It's be great if they were reverted to vanilla state, but unfortunately they aren't.

**Comment by phobos2077** [comment]
Sounds like the updated maps are not perfect, but still better than what's already in master. So we're only improving things with the merge? Maybe later someone could clean them up even more to be closer to vanilla, but we have what we have.

**Comment by Lexx2k** [comment]
> It's be great if they were reverted to vanilla state, but unfortunately they aren't.

I didn't said they are reverted to vanilla. Just that they are better now than before.

**Comment by burner1024** [comment]
> I didn't said they are reverted to vanilla, just that they are better now than before.

I didn't say you said that.

I want:
- less differences between UP and RP, so that they are easier to maintain.
- small, atomic commits that can be reverted invididually.
- proper descriptions for those commits, so that it's clear what's even happening in the repo.

This change is the exact opposite of all that, which is why I have a problem with it.

**Comment by phobos2077** [comment]
As I understand, map changes were all made as one big pass to clean up the maps. Because map changes involve art/proto edits, it's too much work to try and somehow split them into pieces. It's just one big feature. I don't see how we can turn it into "small atomic commits". I get it, when changes are small they are easier to track and revert. But this is inherently a big feature. You can't turn it into a bunch of small features.

As I suggested, let's do more testing of these maps (or you can also check them yourself). If there's no major issues, merge. Or just merge right now and let the possible issues be discovered and fixed in their own course. 

When you took the RP initially, it was just like that - a big pile of some else's work that you maintained. It's the same thing but on a smaller scale. Can't expect all changes to be small tweaks.

**Comment by burner1024** [comment]
I don't agree that it's inherently a big feature. It's made into one.
Map changes do not involve art and proto edits. Those should not even be edited, new ones can be added as required and that should be enough.
If it was properly designed from the beginning, it'd be easy to follow. Now it's the proverbial suitcase without a handle.

I'm not sure what to do with it, but anyway there's a dozen other issues in UPU and RPU repos, so there's time to think.

**Comment by phobos2077** [comment]
Well I've made a suggestion what to do with it, you've yet to explain why you ignore it. Unless you're willing to dissect and re-make all these changes yourself, you can't expect people to repeat their work in a way that suits your vision of "due process". This is not a commercial project, it's a hobby, people do this work in their spare time. We should respect that.

**Comment by burner1024** [comment]
I don't expect anything, just explain why I'm not merging and don't promise to merge.
I refer to design of the patch, not map changes in it.

**Comment by phobos2077** [comment]
> I don't expect anything, just explain why I'm not merging and don't promise to merge.

Sorry, but I don't understand the explanation. You said you want to have small, atomic changes. But artistic redesign is not the same as code. Imagine if you ask a painter to explain and document every stroke of paint he made before the painting can be accepted in the gallery? You can only take in the whole painting and either accept it as a whole, or not.

> I refer to design of the patch, not map changes in it.

Can you please be less cryptic and elaborate so we don't go in circles any longer? What do you mean by "design of the patch" exactly and how it can be improved?

Getting back to my suggestion, why is just testing the whole thing and applying fixes (if needed) on top is not acceptable to you? You can't have the same maps in UP and RPU because they are inherently different beasts. At least originally, UP was about fixing bugs in vanilla game, without any design changes or additions. RPU is a community version of "uncut" Fallout 2, basically a mod. It always had some very controversial and opinionated features, but for the lack of a better alternative (apart from Megamod), people played it. And you choose Killap's mod as a basis for this project, despite it having all these map differences. 

With all that said, I really struggle to understand how this new redesign (from the author of the first redesign) can possible make things worse and not better?

**Comment by burner1024** [comment]
> You can only take in the whole painting and either accept it as a whole, or not.

A bad analogy is like a kitten with a door. A hundred maps is not a painting.

> If you don't like the end result

I don't know anything about end result other than what I heard, which is generally positive. (Although in my experience, sloppy processes yield poorer results more often.)

> why is just testing the whole thing and applying fixes (if needed) on top is not acceptable to you?

Just because I did it once, doesn't mean I want to go all over again.

> You can't have the same maps in UP and RPU because they are inherently different beasts

You can, or you can try, at least. The eventual goal for UPU and RPU is to become more convergent, and possibly modular, so RPU additions could be enabled or disabled at will.

> With all that said, I really struggle to understand how this new redesign (from the author of the first redesign) can possible make things worse and not better?

I don't know if it's better or worse, but I know it's more work.

**Comment by phobos2077** [comment]
> Just because I did it once, doesn't mean I want to go all over again.

Nobody asking YOU to test it. I meant the bigger community. Whoever is testing already and whoever else will be interested to try it out.


> You can, or you can try, at least. The eventual goal for UPU and RPU is to become more convergent, and possibly modular, so RPU additions could be enabled or disabled at will.

To make them "convergent" wouldn't you want the maps to be closer to vanilla? That's what this redesign does, from what I've heard. So that's a reason **for** merge not **against** it.


> I don't know if it's better or worse, but I know it's more work.

What work? Clicking merge button?

**Comment by phobos2077** [comment]
I guess there is no point keeping this open. I will maintain this branch as a mod on nexus in the meantime: https://www.nexusmods.com/fallout2/mods/73/

Please reconsider merging this in future. In the absence of killap, since this comes from one of RP original devs, it's as official as it gets. It's been a year since this came out. People played it, bugs were fixes. What are we waiting for? Blessing from killap?

**Pull request closed without merging**
